# Generated by Django 6.0.1 on 2026-01-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('salary', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=200)),
                ('experience', models.PositiveIntegerField()),
                ('age', models.PositiveIntegerField()),
                ('email', models.CharField(max_length=200, unique=True)),
                ('phone', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
